### PHN Technology Internship 

Name- Yashshree Kirad

College - Pune Vidhyarthi Griha's College of Engineering and Technology

Phone - 8888126700

Task 4

In [11]:
import numpy as np

# Create a NumPy array
array1 = np.array([1, 2, 3, 4, 5])

# Print the shape of the array
print("Shape of the array:", array1.shape)

# Reshape the array into a 2D array with 2 rows and 3 columns
array2 = np.pad(array1, (0, 1), mode='constant').reshape(2, 3)

# Print the shape of the new array
print("Shape of the new array:", array2.shape)

# Create a second NumPy array
array3 = np.array([6, 7, 8, 9, 10])

# Reshape the second array to match the shape of the first array
array3 = np.resize(array3, (2, 3))

# Concatenate the two arrays vertically
result = np.concatenate((array2, array3.reshape(2, 3)), axis=0)

# Print the resulting array
print("Resulting array:")
print(result)

# Compute the mean, median, and standard deviation of the resulting array
mean = np.mean(result)
median = np.median(result)
std_dev = np.std(result)

print("\nMean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Shape of the array: (5,)
Shape of the new array: (2, 3)
Resulting array:
[[ 1  2  3]
 [ 4  5  0]
 [ 6  7  8]
 [ 9 10  6]]

Mean: 5.083333333333333
Median: 5.5
Standard Deviation: 3.0402393911591163
